//! The seven NewAPI log-type fixtures, asserted verbatim.
//!
//! # Why these are literals and not constructed rows
//!
//! Every payload here is copied from an observed panel response rather than
//! built from the adapter's own types. That matters for one specific reason: the
//! mock-panel handlers in `newapi.rs` were written by the same author as the
//! parser, so a misreading of the protocol would be invisible — both sides would
//! agree on the same wrong shape. Feeding the parser raw JSON that was never
//! generated by our own code is what breaks that symmetry.
//!
//! The type values themselves are transcribed from `model/log.go` at
//! `QuantumNous/new-api` main, where they are pinned integers:
//!
//! ```go
//! // don't use iota, avoid change log type value
//! const (LogTypeUnknown = 0; LogTypeTopup = 1; LogTypeConsume = 2; LogTypeManage = 3
//! //        LogTypeSystem = 4; LogTypeError = 5; LogTypeRefund = 6; LogTypeLogin = 7)
//! ```
//!
//! Several published descriptions of these endpoints disagree with each other on
//! the values of 3 and 4. Reading the source is the only way to be sure, and
//! these tests are the record that the mapping in the adapter matches it.

#![cfg(feature = "newapi")]

use zroutery_core::account::adapters::newapi::{
    interpret_log, read_system_signal, LogContext, NewApiLogItem, LOG_TYPE_CONSUME, LOG_TYPE_ERROR,
    LOG_TYPE_LOGIN, LOG_TYPE_MANAGE, LOG_TYPE_REFUND, LOG_TYPE_SYSTEM, LOG_TYPE_TOPUP,
    LOG_TYPE_UNKNOWN,
};
use zroutery_core::account::resource::{ResourceEffect, ResourceEventKind};
use zroutery_core::account::AccountId;

/// Credit units per US dollar, NewAPI's `common.QuotaPerUnit`.
const QUOTA_PER_UNIT: f64 = 500_000.0;

fn parse(json: &str) -> NewApiLogItem {
    serde_json::from_str(json).unwrap_or_else(|e| panic!("fixture must decode: {e}\n{json}"))
}

fn interpret(item: &NewApiLogItem) -> zroutery_core::account::ObservedResourceEvent {
    let id = AccountId("acct-1".into());
    let ctx = LogContext::usd(&id, QUOTA_PER_UNIT);
    interpret_log(item, &ctx).unwrap_or_else(|| panic!("type {} must be an event", item.log_type))
}

// ── Fixture A — consumption ───────────────────────────────────────────────

const CONSUME: &str = r#"{
    "type": 2,
    "channel": 54,
    "token_id": 596910,
    "prompt_tokens": 44814,
    "completion_tokens": 91,
    "quota": 9530
}"#;

#[test]
fn fixture_a_consume_is_a_consumption_on_channel_54_for_9530() {
    let event = interpret(&parse(CONSUME));
    assert_eq!(event.event_kind, ResourceEventKind::Consumption);
    assert_eq!(event.channel_id, Some(54));
    assert_eq!(event.raw_type, Some(LOG_TYPE_CONSUME));

    let amount = event
        .resource_effect
        .amount()
        .expect("a consumption's charge is established from its own row");
    assert_eq!(
        amount.provider_value,
        Some(9530.0),
        "quota = 9530 is recorded verbatim in the provider's own unit"
    );
    assert!(
        (amount.value - 9_530.0 / QUOTA_PER_UNIT).abs() < 1e-12,
        "and normalised for display: {amount:?}"
    );
    assert_eq!(event.metadata_value("newapi.log.raw_quota"), Some("9530"));
}

// ── Fixture B — check-in ───────────────────────────────────────────────────

const CHECKIN: &str = r#"{
    "type": 4,
    "content": "每日签到成功，增加额度 ＄25.000000 额度",
    "quota": 0,
    "channel": 0,
    "token_id": 0,
    "prompt_tokens": 0,
    "completion_tokens": 0
}"#;

#[test]
fn fixture_b_checkin_is_a_system_grant_with_a_detected_reward() {
    let item = parse(CHECKIN);
    let event = interpret(&item);

    assert_eq!(event.event_kind, ResourceEventKind::SystemGrant);
    assert_eq!(event.raw_type, Some(LOG_TYPE_SYSTEM));

    // The reward is recognised as a check-in reward, and by two independent
    // signals rather than by matching this sentence.
    let signal = read_system_signal(&item.content);
    assert!(
        signal.indicates_checkin_reward(),
        "a check-in reward must be detected from this payload: {signal:?}"
    );
    assert!(signal.reward_shaped, "an amount is rendered");
    assert!(signal.mentions_checkin, "and the row names a check-in");
}

#[test]
fn fixture_b_carries_no_request_scoped_fields() {
    let event = interpret(&parse(CHECKIN));
    assert_eq!(event.channel_id, None);
    assert_eq!(event.request_id, None);
    assert_eq!(event.model, None);
    assert!(!event.metadata.contains_key("newapi.token_id"));
    assert!(!event.metadata.contains_key("newapi.group"));
    assert!(
        !event.metadata.contains_key("newapi.use_time_secs"),
        "a grant is not a request that took a measurable time"
    );
}

#[test]
fn fixture_b_resource_effect_is_not_the_log_quota() {
    // The central assertion of the whole resource-observation layer. The row says
    // quota = 0; the account really was credited. Reading the row's `quota` as a
    // balance delta would credit nothing for a reward that arrived, and reading it
    // as *any* signed number would be inventing one.
    let event = interpret(&parse(CHECKIN));
    let raw: f64 = event
        .metadata_value("newapi.log.raw_quota")
        .expect("the raw column is always kept")
        .parse()
        .unwrap();
    assert_eq!(raw, 0.0);

    assert_eq!(
        event.resource_effect,
        ResourceEffect::Unobserved,
        "nothing in this row establishes an amount"
    );
    assert_eq!(event.balance_delta(), None);
    assert!(!event.moved_resource());
    assert_ne!(
        event.resource_effect,
        ResourceEffect::Credited {
            amount: zroutery_core::account::resource::ResourceAmount::normalised(raw, "USD"),
        },
        "and certainly not a zero credit"
    );
}

#[test]
fn fixture_b_recovers_the_rendered_amount_but_does_not_promote_it() {
    // The amount is recoverable from the text — and `logger.LogQuota` is what
    // renders it, which is why the *amount* survives a fork rewording the
    // sentence around it. It stays metadata in the instance's display currency
    // because that is not a balance figure.
    let event = interpret(&parse(CHECKIN));
    let amount: f64 = event
        .metadata_value("newapi.system.display_amount")
        .expect("a rendered amount is recorded")
        .parse()
        .unwrap();
    assert!((amount - 25.0).abs() < 1e-9);
    assert_eq!(
        event.metadata_value("newapi.system.display_symbol"),
        Some("＄")
    );
    assert_eq!(event.resource_effect, ResourceEffect::Unobserved);
}

// ── Fixture C — error ──────────────────────────────────────────────────────

#[test]
fn fixture_c_error_keeps_its_request_identifiers() {
    let item = parse(
        r#"{
            "type": 5,
            "content": "upstream 502",
            "channel": 54,
            "model_name": "gpt-4o",
            "token_id": 596910,
            "group": "default",
            "use_time": 3,
            "is_stream": true,
            "request_id": "req-2f9c",
            "upstream_request_id": "up-77ab",
            "quota": 0
        }"#,
    );
    let event = interpret(&item);
    assert_eq!(event.event_kind, ResourceEventKind::Error);
    assert_eq!(event.raw_type, Some(LOG_TYPE_ERROR));
    assert_eq!(event.request_id.as_deref(), Some("req-2f9c"));
    assert_eq!(event.channel_id, Some(54));
    assert_eq!(event.model.as_deref(), Some("gpt-4o"));
    assert_eq!(event.metadata_value("newapi.group"), Some("default"));
    assert_eq!(event.metadata_value("newapi.use_time_secs"), Some("3"));
    assert_eq!(event.metadata_value("newapi.is_stream"), Some("true"));

    // `RecordErrorLog` writes `Quota: 0` deliberately: an error row records a
    // request that was attempted and did not settle. That is a finding.
    assert_eq!(event.resource_effect, ResourceEffect::NoChange);
    assert!(!event.event_kind.is_resource_bearing());
}

// ── Fixture D — refund ─────────────────────────────────────────────────────

#[test]
fn fixture_d_refund_credits_back_what_a_consumption_debited() {
    let item = parse(r#"{ "type": 6, "quota": 9530, "channel": 54 }"#);
    let event = interpret(&item);
    assert_eq!(event.event_kind, ResourceEventKind::Refund);
    assert_eq!(event.raw_type, Some(LOG_TYPE_REFUND));
    match &event.resource_effect {
        ResourceEffect::Credited { amount } => {
            assert_eq!(amount.provider_value, Some(9530.0));
        }
        other => panic!("a refund credits; got {other:?}"),
    }
    assert!(event.moved_resource());

    // Kept distinct from a replenishment: a refund reverses a charge and can be
    // reversed again, so a ledger that merges the two cancels in the wrong order.
    assert_ne!(event.event_kind, ResourceEventKind::Replenishment);
}

// ── Fixture E — top-up ─────────────────────────────────────────────────────

#[test]
fn fixture_e_topup_is_a_replenishment_that_states_no_amount() {
    let item = parse(r#"{ "type": 1, "content": "兑换码充值成功", "quota": 0, "channel": 0 }"#);
    let event = interpret(&item);
    assert_eq!(event.event_kind, ResourceEventKind::Replenishment);
    assert_eq!(event.raw_type, Some(LOG_TYPE_TOPUP));
    assert!(event.event_kind.is_resource_bearing());

    // `RecordTopupLog` leaves `quota` unset, so this row establishes that the
    // account was credited but not by how much. Reporting a measured zero would
    // state that a payment moved nothing.
    assert_eq!(event.resource_effect, ResourceEffect::Unobserved);
    assert_eq!(event.balance_delta(), None);
}

// ── Fixture F — management ─────────────────────────────────────────────────

#[test]
fn fixture_f_manage_is_management_and_never_a_resource_movement() {
    let item = parse(r#"{ "type": 3, "content": "修改用户额度", "quota": 500000, "channel": 0 }"#);
    let event = interpret(&item);
    assert_eq!(event.event_kind, ResourceEventKind::Management);
    assert_eq!(event.raw_type, Some(LOG_TYPE_MANAGE));

    // A non-zero `quota` on a management row must not become either a charge or
    // a credit. `RecordLogWithAdminInfo` routes these to `AuditLog` and writes no
    // row at all, so a `type=3` row here is a legacy record either way.
    assert_eq!(event.resource_effect, ResourceEffect::Unobserved);
    assert!(!event.event_kind.is_resource_bearing());
    assert_ne!(event.event_kind, ResourceEventKind::Consumption);
    assert_ne!(event.event_kind, ResourceEventKind::Replenishment);
}

// ── Fixture G — login ──────────────────────────────────────────────────────

#[test]
fn fixture_g_login_is_a_login_that_moves_nothing() {
    let item = parse(r#"{ "type": 7, "content": "用户登录", "quota": 0 }"#);
    let event = interpret(&item);
    assert_eq!(event.event_kind, ResourceEventKind::Login);
    assert_eq!(event.raw_type, Some(LOG_TYPE_LOGIN));
    assert_eq!(event.resource_effect, ResourceEffect::NoChange);
    assert!(!event.event_kind.is_resource_bearing());
}

// ── Cross-fixture invariants ───────────────────────────────────────────────

#[test]
fn only_a_consumption_reproduces_the_naive_quota_rule_and_that_is_deliberate() {
    // The rule `balance_delta = log.quota` applied without regard to type would
    // give: consume -9530, check-in 0, error 0, refund +9530, topup 0,
    // manage 0, login 0. Every zero there is wrong, and the check-in one is the
    // expensive one — it credits nothing for a reward that really arrived.
    //
    // Consumption is the single case where agreement is *correct*, because
    // `RecordConsumeLog` writes the computed charge into that column. That it
    // agrees is therefore evidence the rule is type-dependent and
    // write-site-derived, not evidence that the naive rule works.
    let cases: [(&str, i64, Option<f64>); 7] = [
        (CONSUME, LOG_TYPE_CONSUME, Some(-9_530.0 / QUOTA_PER_UNIT)),
        (CHECKIN, LOG_TYPE_SYSTEM, None),
        (r#"{ "type": 5, "quota": 0 }"#, LOG_TYPE_ERROR, None),
        (
            r#"{ "type": 6, "quota": 9530 }"#,
            LOG_TYPE_REFUND,
            Some(9_530.0 / QUOTA_PER_UNIT),
        ),
        (r#"{ "type": 1, "quota": 0 }"#, LOG_TYPE_TOPUP, None),
        (r#"{ "type": 3, "quota": 500000 }"#, LOG_TYPE_MANAGE, None),
        (r#"{ "type": 7, "quota": 0 }"#, LOG_TYPE_LOGIN, None),
    ];

    for (json, expected_type, expected_delta) in cases {
        let item = parse(json);
        assert_eq!(item.log_type, expected_type);
        let event = interpret(&item);

        // The naive rule, in the same normalised units `balance_delta` uses.
        let naive = -item.quota as f64 / QUOTA_PER_UNIT;
        match expected_delta {
            Some(delta) => assert!(
                (event.balance_delta().expect("a movement") - delta).abs() < 1e-12,
                "type {expected_type}: a movement was established, and it is what the \
                 row's own charge column says"
            ),
            None => assert_eq!(
                event.balance_delta(),
                None,
                "type {expected_type}: nothing established an amount, so the naive rule's \
                 {} would be invented",
                if naive == 0.0 {
                    "zero".to_string()
                } else {
                    format!("{naive}")
                }
            ),
        }
    }
}

#[test]
fn every_verified_type_is_covered_by_exactly_one_fixture() {
    // Guards the mapping against a value silently changing meaning: a new type
    // constant added to the adapter must arrive here too.
    let seen: Vec<i64> = [
        CONSUME,
        CHECKIN,
        r#"{ "type": 5 }"#,
        r#"{ "type": 6 }"#,
        r#"{ "type": 1 }"#,
        r#"{ "type": 3 }"#,
        r#"{ "type": 7 }"#,
    ]
    .iter()
    .map(|json| parse(json).log_type)
    .collect();

    assert_eq!(
        seen,
        vec![
            LOG_TYPE_CONSUME,
            LOG_TYPE_SYSTEM,
            LOG_TYPE_ERROR,
            LOG_TYPE_REFUND,
            LOG_TYPE_TOPUP,
            LOG_TYPE_MANAGE,
            LOG_TYPE_LOGIN,
        ]
    );
    assert_eq!(LOG_TYPE_UNKNOWN, 0);
}

#[test]
fn the_mapping_is_not_the_old_documented_one() {
    // Pins the specific disagreement this repository hit: `type=3` is Manage and
    // `type=4` is System in the current source. Any mapping that reads 3 as a
    // system log, or 4 as an error, fails here.
    assert_eq!(LOG_TYPE_MANAGE, 3);
    assert_eq!(LOG_TYPE_SYSTEM, 4);
    assert_eq!(LOG_TYPE_ERROR, 5);

    let id = AccountId("acct-1".into());
    let ctx = LogContext::usd(&id, QUOTA_PER_UNIT);
    let manage = interpret_log(&parse(r#"{ "type": 3 }"#), &ctx).unwrap();
    let system = interpret_log(&parse(r#"{ "type": 4 }"#), &ctx).unwrap();
    assert_eq!(manage.event_kind, ResourceEventKind::Management);
    assert_eq!(system.event_kind, ResourceEventKind::SystemGrant);
    assert_ne!(
        system.event_kind,
        ResourceEventKind::Error,
        "type 4 is a system grant, not a generic error"
    );
}
