//! Feedback and training sample data models for Zroutery.
//!
//! Feedback is evaluation signals *separate* from [`Outcome`](crate::outcome::Outcome).
//! Outcome = facts. Feedback = evaluation.
//!
//! The [`TrainingSample`] type combines decision, features, outcome, and feedback
//! into a single schema boundary that Stage 6 will consume.

use serde::{Deserialize, Serialize};

use crate::outcome::{failure_class_wire_name, Outcome};

// ---------------------------------------------------------------------------
// FeedbackSignal
// ---------------------------------------------------------------------------

/// A single feedback signal for a completed outcome.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum FeedbackSignal {
    /// User explicitly rated the response.
    ExplicitRating { score: f64 },
    /// User retried or regenerated the response.
    RetryRequested,
    /// User continued the conversation (implicit satisfaction).
    ConversationContinued,
    /// User abandoned the conversation.
    ConversationAbandoned,
    /// Tool execution succeeded or failed.
    ToolExecution { success: bool },
    /// Response was truncated or incomplete.
    Incomplete,
}

impl FeedbackSignal {
    pub fn is_explicit_rating(&self) -> bool {
        matches!(self, Self::ExplicitRating { .. })
    }

    pub fn rating(&self) -> Option<f64> {
        match self {
            Self::ExplicitRating { score } if score.is_finite() => Some(*score),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// FeedbackSource
// ---------------------------------------------------------------------------

/// The origin of a feedback signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FeedbackSource {
    /// From the client/user directly.
    Client,
    /// Inferred by the system.
    System,
    /// Imported from external data.
    Imported,
}

// ---------------------------------------------------------------------------
// DataOrigin
// ---------------------------------------------------------------------------

/// Where the data came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DataOrigin {
    /// Generated by Zroutery runtime.
    Native,
    /// Imported from CC Switch or other sources.
    Imported,
    /// Synthetic/generated for testing.
    Synthetic,
}

// ---------------------------------------------------------------------------
// Feedback
// ---------------------------------------------------------------------------

/// Feedback signals for a completed outcome.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Feedback {
    pub outcome_id: String,
    pub timestamp: i64,
    pub signals: Vec<FeedbackSignal>,
    pub source: FeedbackSource,
    pub data_origin: DataOrigin,
}

impl Feedback {
    /// Whether this record contains no actual signal.  An absent signal is not
    /// converted into a positive or negative rating.
    pub fn is_empty(&self) -> bool {
        self.signals.is_empty()
    }

    pub fn has_explicit_rating(&self) -> bool {
        self.signals.iter().any(FeedbackSignal::is_explicit_rating)
    }

    /// Return a rating only when exactly one finite explicit rating exists.
    pub fn rating(&self) -> Option<f64> {
        let mut ratings = self.signals.iter().filter_map(FeedbackSignal::rating);
        let first = ratings.next()?;
        ratings.next().is_none().then_some(first)
    }

    pub fn matches_outcome(&self, outcome: &Outcome) -> bool {
        self.outcome_id == outcome.outcome_id
    }

    pub fn validate(&self) -> Result<(), String> {
        if self.outcome_id.trim().is_empty() {
            return Err("feedback outcome_id must not be empty".to_string());
        }
        if self.signals.is_empty() {
            return Err("feedback with no signal must be represented as None".to_string());
        }
        for (index, signal) in self.signals.iter().enumerate() {
            if let FeedbackSignal::ExplicitRating { score } = signal {
                if !score.is_finite() {
                    return Err(format!("feedback signal[{index}] rating is not finite"));
                }
            }
        }
        Ok(())
    }

    /// Pure, checked conversion from an outcome plus explicitly supplied
    /// signals.  No outcome fact is converted into a user signal.
    pub fn try_from_outcome(
        outcome: &Outcome,
        signals: Vec<FeedbackSignal>,
        timestamp: i64,
        source: FeedbackSource,
        data_origin: DataOrigin,
    ) -> Result<Option<Self>, String> {
        outcome.validate()?;
        if signals.is_empty() {
            return Ok(None);
        }
        let feedback = Self {
            outcome_id: outcome.outcome_id.clone(),
            timestamp,
            signals,
            source,
            data_origin,
        };
        feedback.validate()?;
        Ok(Some(feedback))
    }

    /// Compatibility form that treats an empty signal list as `None`.
    pub fn from_outcome(
        outcome: &Outcome,
        signals: Vec<FeedbackSignal>,
        timestamp: i64,
        source: FeedbackSource,
        data_origin: DataOrigin,
    ) -> Option<Self> {
        Self::try_from_outcome(outcome, signals, timestamp, source, data_origin)
            .ok()
            .flatten()
    }

    /// Client-origin native feedback convenience constructor.
    pub fn from_outcome_signals(
        outcome: &Outcome,
        signals: Vec<FeedbackSignal>,
        timestamp: i64,
    ) -> Option<Self> {
        Self::from_outcome(
            outcome,
            signals,
            timestamp,
            FeedbackSource::Client,
            DataOrigin::Native,
        )
    }

    pub fn try_from_optional_signals(
        outcome: &Outcome,
        signals: Option<Vec<FeedbackSignal>>,
        timestamp: i64,
        source: FeedbackSource,
        data_origin: DataOrigin,
    ) -> Result<Option<Self>, String> {
        Self::try_from_outcome(outcome, signals.unwrap_or_default(), timestamp, source, data_origin)
    }
}

/// Pure Outcome-to-Feedback bridge.  `None` means no signal was supplied;
/// success/failure status alone never creates a rating.
pub fn feedback_from_outcome(
    outcome: &Outcome,
    signals: Option<Vec<FeedbackSignal>>,
    timestamp: i64,
    source: FeedbackSource,
    data_origin: DataOrigin,
) -> Option<Feedback> {
    Feedback::from_outcome(outcome, signals.unwrap_or_default(), timestamp, source, data_origin)
}

/// Checked variant for adapters that must distinguish an invalid outcome from
/// a valid no-signal outcome.
pub fn try_feedback_from_outcome(
    outcome: &Outcome,
    signals: Option<Vec<FeedbackSignal>>,
    timestamp: i64,
    source: FeedbackSource,
    data_origin: DataOrigin,
) -> Result<Option<Feedback>, String> {
    Feedback::try_from_outcome(outcome, signals.unwrap_or_default(), timestamp, source, data_origin)
}

pub fn outcome_to_feedback(
    outcome: &Outcome,
    signals: Option<Vec<FeedbackSignal>>,
    timestamp: i64,
    source: FeedbackSource,
    data_origin: DataOrigin,
) -> Option<Feedback> {
    feedback_from_outcome(outcome, signals, timestamp, source, data_origin)
}

// ---------------------------------------------------------------------------
// OutcomeSummary
// ---------------------------------------------------------------------------

/// Serializable summary of an Outcome for training purposes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct OutcomeSummary {
    pub success: bool,
    pub final_status: String,
    pub initial_model: String,
    pub final_model: String,
    pub fallback_count: u32,
    pub total_latency_ms: f64,
    pub ttft_ms: Option<f64>,
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub failure_class: Option<String>,
}

impl OutcomeSummary {
    /// Build the legacy summary shape from a validated Outcome.  New ML code
    /// should use the canonical sample in `ml::dataset`, which also carries
    /// planned/last-attempted/served identity and optional Feedback.
    pub fn try_from_outcome(outcome: &Outcome) -> Result<Self, String> {
        outcome.validate()?;
        let identity = outcome.identity();
        let initial_model = identity
            .planned
            .as_ref()
            .map(|candidate| candidate.model.clone())
            .unwrap_or_else(|| outcome.initial_model.clone());
        let final_model = identity
            .served
            .as_ref()
            .map(|candidate| candidate.model.clone())
            .unwrap_or_default();
        Ok(Self {
            success: outcome.is_terminal_success(),
            final_status: serde_json::to_value(outcome.final_status)
                .ok()
                .and_then(|value| value.as_str().map(str::to_owned))
                .unwrap_or_else(|| format!("{:?}", outcome.final_status).to_lowercase()),
            initial_model,
            final_model,
            fallback_count: outcome.fallback_count,
            total_latency_ms: outcome.total_latency_ms,
            ttft_ms: if outcome.is_terminal_success() {
                outcome.ttft_ms
            } else {
                None
            },
            input_tokens: outcome.usage.as_ref().map_or(0, |usage| usage.input_tokens),
            output_tokens: outcome.usage.as_ref().map_or(0, |usage| usage.output_tokens),
            failure_class: outcome
                .terminal_failure_facts()
                .map(|facts| failure_class_wire_name(facts.class).to_string()),
        })
    }

    pub fn from_outcome(outcome: &Outcome) -> Result<Self, String> {
        Self::try_from_outcome(outcome)
    }
}

// ---------------------------------------------------------------------------
// TrainingSample
// ---------------------------------------------------------------------------

/// A training sample combining decision, features, outcome, and feedback.
///
/// This is the schema boundary -- Stage 6 will consume these.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TrainingSample {
    pub sample_id: String,
    pub outcome_id: String,
    pub decision_id: Option<String>,
    pub timestamp: i64,
    pub data_origin: DataOrigin,
    /// The outcome (objective facts).
    pub outcome_summary: OutcomeSummary,
    /// Feedback signals (evaluation).
    pub feedback: Vec<FeedbackSignal>,
    /// Feature snapshot at decision time (placeholder for Stage 6).
    pub features: Option<serde_json::Value>,
}

impl TryFrom<&Outcome> for OutcomeSummary {
    type Error = String;

    fn try_from(outcome: &Outcome) -> Result<Self, Self::Error> {
        Self::try_from_outcome(outcome)
    }
}

impl TrainingSample {
    /// Compatibility conversion from the original Stage 6 schema to the
    /// canonical outcome boundary.  It is intentionally lossless only for the
    /// fields that this legacy shape can represent; new code should consume
    /// `ml::dataset::OutcomeTrainingSample`.
    pub fn from_outcome(outcome: &Outcome) -> Result<Self, String> {
        Self::from_outcome_with(
            outcome,
            format!("feedback-sample-{}", outcome.outcome_id),
            None,
            DataOrigin::Native,
            None,
        )
    }

    pub fn from_outcome_with(
        outcome: &Outcome,
        sample_id: impl Into<String>,
        features: Option<serde_json::Value>,
        data_origin: DataOrigin,
        feedback: Option<&Feedback>,
    ) -> Result<Self, String> {
        outcome.validate()?;
        if let Some(feedback) = feedback {
            feedback.validate()?;
            if !feedback.matches_outcome(outcome) {
                return Err("feedback outcome_id does not match outcome".to_string());
            }
        }
        Ok(Self {
            sample_id: sample_id.into(),
            outcome_id: outcome.outcome_id.clone(),
            decision_id: outcome.decision_id.clone(),
            timestamp: outcome.timestamp,
            data_origin,
            outcome_summary: OutcomeSummary::try_from_outcome(outcome)?,
            feedback: feedback
                .map(|feedback| feedback.signals.clone())
                .unwrap_or_default(),
            features,
        })
    }

    pub fn with_feedback(mut self, feedback: Option<&Feedback>) -> Result<Self, String> {
        if let Some(feedback) = feedback {
            feedback.validate()?;
            if feedback.outcome_id != self.outcome_id {
                return Err("feedback outcome_id does not match sample".to_string());
            }
            self.feedback = feedback.signals.clone();
        } else {
            self.feedback.clear();
        }
        Ok(self)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- FeedbackSignal serde for each variant --

    #[test]
    fn feedback_signal_explicit_rating() {
        let signal = FeedbackSignal::ExplicitRating { score: 4.5 };
        let json = serde_json::to_string(&signal).unwrap();
        assert!(json.contains("explicit_rating"));
        assert!(json.contains("4.5"));
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        match restored {
            FeedbackSignal::ExplicitRating { score } => assert_eq!(score, 4.5),
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn feedback_signal_retry_requested() {
        let signal = FeedbackSignal::RetryRequested;
        let json = serde_json::to_string(&signal).unwrap();
        assert_eq!(json, r#"{"type":"retry_requested"}"#);
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        assert!(matches!(restored, FeedbackSignal::RetryRequested));
    }

    #[test]
    fn feedback_signal_conversation_continued() {
        let signal = FeedbackSignal::ConversationContinued;
        let json = serde_json::to_string(&signal).unwrap();
        assert_eq!(json, r#"{"type":"conversation_continued"}"#);
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        assert!(matches!(restored, FeedbackSignal::ConversationContinued));
    }

    #[test]
    fn feedback_signal_conversation_abandoned() {
        let signal = FeedbackSignal::ConversationAbandoned;
        let json = serde_json::to_string(&signal).unwrap();
        assert_eq!(json, r#"{"type":"conversation_abandoned"}"#);
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        assert!(matches!(restored, FeedbackSignal::ConversationAbandoned));
    }

    #[test]
    fn feedback_signal_tool_execution() {
        let signal = FeedbackSignal::ToolExecution { success: true };
        let json = serde_json::to_string(&signal).unwrap();
        assert!(json.contains("tool_execution"));
        assert!(json.contains(r#""success":true"#));
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        match restored {
            FeedbackSignal::ToolExecution { success } => assert!(success),
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn feedback_signal_tool_execution_failure() {
        let signal = FeedbackSignal::ToolExecution { success: false };
        let json = serde_json::to_string(&signal).unwrap();
        assert!(json.contains(r#""success":false"#));
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        match restored {
            FeedbackSignal::ToolExecution { success } => assert!(!success),
            _ => panic!("wrong variant"),
        }
    }

    #[test]
    fn feedback_signal_incomplete() {
        let signal = FeedbackSignal::Incomplete;
        let json = serde_json::to_string(&signal).unwrap();
        assert_eq!(json, r#"{"type":"incomplete"}"#);
        let restored: FeedbackSignal = serde_json::from_str(&json).unwrap();
        assert!(matches!(restored, FeedbackSignal::Incomplete));
    }

    // -- DataOrigin serde --

    #[test]
    fn data_origin_variants_round_trip() {
        let variants = [DataOrigin::Native, DataOrigin::Imported, DataOrigin::Synthetic];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let restored: DataOrigin = serde_json::from_str(&json).unwrap();
            assert_eq!(*v, restored);
        }
    }

    #[test]
    fn data_origin_wire_format() {
        assert_eq!(serde_json::to_string(&DataOrigin::Native).unwrap(), "\"native\"");
        assert_eq!(serde_json::to_string(&DataOrigin::Imported).unwrap(), "\"imported\"");
        assert_eq!(serde_json::to_string(&DataOrigin::Synthetic).unwrap(), "\"synthetic\"");
    }

    // -- FeedbackSource variants --

    #[test]
    fn feedback_source_variants_round_trip() {
        let variants = [FeedbackSource::Client, FeedbackSource::System, FeedbackSource::Imported];
        for v in &variants {
            let json = serde_json::to_string(v).unwrap();
            let restored: FeedbackSource = serde_json::from_str(&json).unwrap();
            assert_eq!(*v, restored);
        }
    }

    #[test]
    fn feedback_source_wire_format() {
        assert_eq!(serde_json::to_string(&FeedbackSource::Client).unwrap(), "\"client\"");
        assert_eq!(serde_json::to_string(&FeedbackSource::System).unwrap(), "\"system\"");
        assert_eq!(serde_json::to_string(&FeedbackSource::Imported).unwrap(), "\"imported\"");
    }

    // -- Feedback construction and round-trip --

    #[test]
    fn feedback_round_trip() {
        let feedback = Feedback {
            outcome_id: "out_abc".to_string(),
            timestamp: 1_700_000_000,
            signals: vec![
                FeedbackSignal::ExplicitRating { score: 3.0 },
                FeedbackSignal::ToolExecution { success: true },
            ],
            source: FeedbackSource::Client,
            data_origin: DataOrigin::Native,
        };
        let json = serde_json::to_string(&feedback).unwrap();
        let restored: Feedback = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.outcome_id, "out_abc");
        assert_eq!(restored.timestamp, 1_700_000_000);
        assert_eq!(restored.signals.len(), 2);
        assert_eq!(restored.source, FeedbackSource::Client);
        assert_eq!(restored.data_origin, DataOrigin::Native);
    }

    // -- TrainingSample construction from Outcome + Feedback --

    #[test]
    fn training_sample_construction() {
        let summary = OutcomeSummary {
            success: true,
            final_status: "success".to_string(),
            initial_model: "gpt-4".to_string(),
            final_model: "gpt-4".to_string(),
            fallback_count: 0,
            total_latency_ms: 350.0,
            ttft_ms: Some(105.0),
            input_tokens: 100,
            output_tokens: 50,
            failure_class: None,
        };

        let sample = TrainingSample {
            sample_id: "samp_001".to_string(),
            outcome_id: "out_abc".to_string(),
            decision_id: Some("dec_123".to_string()),
            timestamp: 1_700_000_000,
            data_origin: DataOrigin::Native,
            outcome_summary: summary,
            feedback: vec![
                FeedbackSignal::ExplicitRating { score: 4.5 },
                FeedbackSignal::ConversationContinued,
            ],
            features: None,
        };

        assert_eq!(sample.sample_id, "samp_001");
        assert_eq!(sample.outcome_id, "out_abc");
        assert_eq!(sample.decision_id, Some("dec_123".to_string()));
        assert!(sample.outcome_summary.success);
        assert_eq!(sample.outcome_summary.input_tokens, 100);
        assert_eq!(sample.feedback.len(), 2);
        assert!(sample.features.is_none());
    }

    #[test]
    fn training_sample_round_trip() {
        let summary = OutcomeSummary {
            success: false,
            final_status: "failed".to_string(),
            initial_model: "gpt-4".to_string(),
            final_model: "claude-3".to_string(),
            fallback_count: 1,
            total_latency_ms: 600.0,
            ttft_ms: None,
            input_tokens: 200,
            output_tokens: 0,
            failure_class: Some("provider_unavailable".to_string()),
        };

        let sample = TrainingSample {
            sample_id: "samp_002".to_string(),
            outcome_id: "out_def".to_string(),
            decision_id: None,
            timestamp: 1_700_000_001,
            data_origin: DataOrigin::Imported,
            outcome_summary: summary,
            feedback: vec![FeedbackSignal::RetryRequested],
            features: Some(serde_json::json!({"latency_bucket": "fast"})),
        };

        let json = serde_json::to_string(&sample).unwrap();
        let restored: TrainingSample = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.sample_id, "samp_002");
        assert_eq!(restored.decision_id, None);
        assert_eq!(restored.data_origin, DataOrigin::Imported);
        assert!(!restored.outcome_summary.success);
        assert_eq!(restored.outcome_summary.fallback_count, 1);
        assert_eq!(restored.outcome_summary.failure_class, Some("provider_unavailable".to_string()));
        assert_eq!(restored.feedback.len(), 1);
        assert!(restored.features.is_some());
    }
}
