//! The named shadow candidate: one verified model commit, attached to the
//! record-only shadow on the serving path.
//!
//! What this module is
//!
//! Until now the serving path held a predictor but named nothing: the shadow
//! engine pins a cold-start root commit in its own constructor and the request
//! pipeline asks the engine to evaluate. That is a working shadow with no
//! artifact behind it — nothing is persisted, nothing is gated, and nothing on
//! disk says which model produced the records. This module supplies the missing
//! half: a frozen commit artifact, compiled into the binary, verified on the
//! way in, and handed to the evaluation seam by explicit name.
//!
//! Where the artifact comes from
//!
//! `shadow_candidate.json`, next to this file, embedded with `include_str!`.
//! Not read from disk at runtime, not named by configuration, not selectable by
//! an environment variable. There is exactly one candidate and it is part of the
//! program, so "which model is this shadow running" has one answer that cannot
//! be changed by a deployment.
//!
//! The artifact is frozen: it was produced once, offline, by the generator in
//! `tests/real_request_shadow_test.rs`, from canonical samples that the
//! production serving path itself collected from real requests made through the
//! production router against a local fake upstream. It is not regenerated by
//! any test, and no test asserts that regenerating it would reproduce it.
//!
//! What verification happens on the way in
//!
//! Three checks, in this order, and the order is chosen so that every refusal
//! is reachable and names something distinct:
//!
//! 1. [`ReplayEngine::verify_checkpoint_integrity`] — does the checkpoint load,
//!    validate against its envelope, and agree with its own parameter checksum?
//!    This runs **first** on purpose: `ModelCommit::verify` also loads the
//!    checkpoint, so running it first would report every checkpoint problem as a
//!    commit problem and leave this check with no state it could ever refuse.
//! 2. [`ModelCommit::verify`] — is this record internally consistent, i.e. does
//!    its content-addressed identity match the content it carries? This is what
//!    catches an edit that leaves the checkpoint valid but changes what it
//!    contains, such as an edited update count.
//! 3. [`ModelEnsemblePredictor::from_model_commit_with_lineage`] — does the
//!    predictor reconstruct from the artifact, and is the retained lineage
//!    complete, linked, cycle-free and model-consistent? A child commit whose
//!    parent record is missing is refused here rather than silently truncated.
//!
//! Check 3 is deliberately stricter than either of the others: it re-verifies
//! every lineage record rather than trusting the commit under consideration to
//! vouch for its ancestors.
//!
//! A failure at any step yields [`ShadowCandidateError`], and the caller —
//! `AppState::new` — turns that into a *withdrawn* attachment. That is
//! fail-closed to the previous behaviour: a corrupt artifact removes a
//! diagnostic capability rather than degrading a served response, and nothing is
//! ever partially attached.
//!
//! What this is not
//!
//! Attaching a candidate is a shadow operation and nothing more. The returned
//! predictor is handed to [`crate::ml::ShadowEngine::evaluate_with`], which
//! returns a record; no code on the request path reads that record's verdict,
//! and this module holds no handle that could make one readable as a routing
//! input. A release verdict is not an activation, and the attachment here says
//! nothing about whether the model is fit to serve — that question belongs to
//! the offline gate, whose answer is recorded, not assumed.

#[cfg(feature = "ml")]
use std::sync::Arc;

#[cfg(feature = "ml")]
use serde::{Deserialize, Serialize};

#[cfg(feature = "ml")]
use crate::ml::model_identity::{ModelCommit, ReplayEngine};
#[cfg(feature = "ml")]
use crate::ml::shadow::ModelEnsemblePredictor;

/// The frozen candidate artifact, compiled into the binary.
///
/// Every byte of this file is part of the program image: there is no runtime
/// path that substitutes a different candidate.
#[cfg(feature = "ml")]
pub const SHADOW_CANDIDATE_ARTIFACT: &str = include_str!("shadow_candidate.json");

/// Envelope version of the artifact file itself.
///
/// Separate from the commit's own envelope version, which is verified by
/// [`ModelCommit::verify`]. This one says "this file has the shape this code
/// expects"; a future artifact shape gets a new number rather than being
/// guessed at.
#[cfg(feature = "ml")]
pub const SHADOW_CANDIDATE_ENVELOPE_VERSION: u32 = 1;

/// The on-disk shape of the artifact file.
///
/// Deliberately not `#[serde(deny_unknown_fields)]`: a future writer may add a
/// descriptive field, and an older reader that ignores it is more honest than
/// one that refuses to start. The fields that carry meaning are the commit and
/// its lineage, and both are verified cryptographically, not structurally.
#[cfg(feature = "ml")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShadowCandidateArtifact {
    /// See [`SHADOW_CANDIDATE_ENVELOPE_VERSION`].
    pub schema_version: u32,
    /// How this artifact was produced, in the words of whoever produced it.
    ///
    /// Carried so a reader of the file learns the provenance without reading
    /// this source file. It is descriptive only and is not part of the commit
    /// identity, so editing it cannot change which model this is.
    pub provenance: String,
    /// The model the lineage belongs to, repeated here so a mismatch between the
    /// file and the commit is visible without deserializing the commit.
    pub model_id: String,
    /// The commit under consideration.
    pub commit: ModelCommit,
    /// The complete root-to-current lineage, ending at [`Self::commit`].
    pub lineage: Vec<ModelCommit>,
}

/// Why a candidate could not be attached.
///
/// Every variant is a refusal that is *reported*, never repaired. A candidate
/// that does not verify is not a candidate.
#[cfg(feature = "ml")]
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ShadowCandidateError {
    /// The embedded artifact is not the shape this code reads.
    #[error("the embedded shadow candidate artifact is unreadable: {reason}")]
    ArtifactUnreadable {
        /// What deserialization said.
        reason: String,
    },

    /// The artifact file carries an envelope version this code does not read.
    #[error(
        "the embedded shadow candidate artifact has envelope version {found}, which this code \
         does not read; supported is {SHADOW_CANDIDATE_ENVELOPE_VERSION}"
    )]
    UnsupportedEnvelope {
        /// The version found in the file.
        found: u32,
    },

    /// The commit record refused the accepted identity verification.
    #[error("the shadow candidate commit '{commit_id}' refused verification: {reason}")]
    CommitRefused {
        /// Which commit.
        commit_id: String,
        /// Why.
        reason: String,
    },

    /// The checkpoint refused integrity verification.
    #[error(
        "the shadow candidate checkpoint for '{commit_id}' is not internally consistent: {reason}"
    )]
    CheckpointRefused {
        /// Which commit's checkpoint.
        commit_id: String,
        /// Why.
        reason: String,
    },

    /// The predictor could not be rebuilt from the artifact.
    #[error("the shadow candidate '{commit_id}' could not become a predictor: {reason}")]
    PredictorRefused {
        /// Which commit.
        commit_id: String,
        /// Why.
        reason: String,
    },

    /// The retained lineage is not the complete root-to-current chain.
    #[error("the shadow candidate lineage for '{commit_id}' is not complete: {reason}")]
    LineageRefused {
        /// Which commit the lineage was supposed to end at.
        commit_id: String,
        /// Why.
        reason: String,
    },
}

/// One verified model commit, ready to be evaluated against a request.
///
/// Immutable and shared. Constructed only by [`ShadowCandidate::from_artifact`],
/// which is the only place the three verifications happen.
#[cfg(feature = "ml")]
#[derive(Clone)]
pub struct ShadowCandidate {
    predictor: Arc<ModelEnsemblePredictor>,
    commit: ModelCommit,
    lineage: Vec<ModelCommit>,
}

/// Structural, and deliberately not the predictor's parameters: the commit id is
/// the identity, and a `Debug` that dumped a model's weights would make every
/// log line that mentions one enormous.
#[cfg(feature = "ml")]
impl std::fmt::Debug for ShadowCandidate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ShadowCandidate")
            .field("commit_id", &self.commit.commit_id.as_str())
            .field("model_id", &self.commit.model_id.as_str())
            .field("parent", &self.commit.parent.as_ref().map(|id| id.as_str()))
            .field("learning_events", &self.commit.learning_event_count)
            .field("lineage_len", &self.lineage.len())
            .finish()
    }
}

#[cfg(feature = "ml")]
impl ShadowCandidate {
    /// The embedded artifact, verified.
    ///
    /// Called once per `AppState`, at construction. A failure here means the
    /// program ships a candidate it cannot verify, and the caller responds by
    /// running with the shadow withdrawn.
    pub fn embedded() -> Result<Self, ShadowCandidateError> {
        Self::from_json(SHADOW_CANDIDATE_ARTIFACT)
    }

    /// Verify and adopt an artifact held as JSON text.
    ///
    /// Split out from [`Self::embedded`] so the persistence round trip and the
    /// refusal paths are testable without the binary's own bytes.
    pub fn from_json(text: &str) -> Result<Self, ShadowCandidateError> {
        let artifact: ShadowCandidateArtifact = serde_json::from_str(text).map_err(|error| {
            ShadowCandidateError::ArtifactUnreadable {
                reason: error.to_string(),
            }
        })?;
        Self::from_artifact(&artifact)
    }

    /// The three verifications, in order, and nothing else.
    pub fn from_artifact(artifact: &ShadowCandidateArtifact) -> Result<Self, ShadowCandidateError> {
        if artifact.schema_version != SHADOW_CANDIDATE_ENVELOPE_VERSION {
            return Err(ShadowCandidateError::UnsupportedEnvelope {
                found: artifact.schema_version,
            });
        }

        let commit = &artifact.commit;
        let commit_id = commit.commit_id.as_str().to_string();

        // 1. The checkpoint the commit points at loads, validates and agrees
        //    with its own parameter checksum. First, so a corrupt checkpoint is
        //    reported as a corrupt checkpoint.
        if !ReplayEngine::verify_checkpoint_integrity(&commit.checkpoint) {
            return Err(ShadowCandidateError::CheckpointRefused {
                commit_id,
                reason: "ReplayEngine::verify_checkpoint_integrity() returned false".to_string(),
            });
        }

        // 2. The record verifies against its own content-addressed identity.
        //    This is the check that catches a file edited by hand in a way that
        //    left the checkpoint internally valid.
        if !commit.verify() {
            return Err(ShadowCandidateError::CommitRefused {
                commit_id,
                reason: "ModelCommit::verify() returned false".to_string(),
            });
        }

        // 3. The predictor reconstructs, and the lineage is complete. The
        //    predictor constructor re-verifies every lineage record, checks
        //    model consistency and parent linkage, and refuses a root with
        //    extra records or a child without its parent.
        let predictor =
            ModelEnsemblePredictor::from_model_commit_with_lineage(commit, &artifact.lineage)
                .map_err(|error| ShadowCandidateError::PredictorRefused {
                    commit_id: commit_id.clone(),
                    reason: error.to_string(),
                })?;

        let lineage = artifact.lineage.clone();
        if lineage.last().map(|entry| entry.commit_id.clone()) != Some(commit.commit_id.clone()) {
            return Err(ShadowCandidateError::LineageRefused {
                commit_id,
                reason: format!(
                    "the lineage ends at '{}', not at the commit under consideration",
                    lineage
                        .last()
                        .map(|entry| entry.commit_id.as_str().to_string())
                        .unwrap_or_else(|| "nothing".to_string())
                ),
            });
        }

        Ok(Self {
            predictor: Arc::new(predictor),
            commit: commit.clone(),
            lineage,
        })
    }

    /// The predictor to hand to the evaluation seam.
    pub fn predictor(&self) -> &ModelEnsemblePredictor {
        &self.predictor
    }

    /// The same predictor, shared.
    ///
    /// The serving path holds this rather than a borrow so the `Arc` outlives
    /// the lock that guards the attachment: prediction then runs with no lock
    /// held at all, which is what makes a withdrawal safe to perform while
    /// requests are in flight.
    pub fn shared_predictor(&self) -> Arc<ModelEnsemblePredictor> {
        Arc::clone(&self.predictor)
    }

    /// The commit under consideration, complete and verified.
    pub fn commit(&self) -> &ModelCommit {
        &self.commit
    }

    /// The verified root-to-current lineage.
    pub fn lineage(&self) -> &[ModelCommit] {
        &self.lineage
    }

    /// The commit id, which is also what every shadow record it produces names.
    pub fn commit_id(&self) -> &str {
        self.commit.commit_id.as_str()
    }
}

/// What the serving path has attached to its shadow.
///
/// Two states and no third. `Attached` names a verified commit; `Withdrawn` is
/// the state this node started in and the state rollback returns to.
///
/// This type exists in every build of the crate, while the candidate it can hold
/// does not. That is deliberate: a withdrawn attachment is a real state in a
/// build with no `ml` feature too — it is simply the only one — and gating the
/// whole type would mean two copies of `AppState`'s construction, which is the
/// kind of duplication that rots.
///
/// The candidate is behind an `Arc` for two reasons that are the same reason:
/// it is one immutable object shared by every request rather than state each
/// request copies, and a candidate carrying its own commit record and lineage is
/// several hundred bytes, which an enum variant should not carry inline beside a
/// variant that carries nothing at all.
#[derive(Debug, Clone, Default)]
pub enum ShadowAttachment {
    /// A verified candidate is attached and will be named in every record.
    #[cfg(feature = "ml")]
    Attached(Arc<ShadowCandidate>),
    /// No candidate. The shadow evaluates against the engine's own cold-start
    /// predictor, exactly as it did before this node.
    #[default]
    Withdrawn,
}

impl ShadowAttachment {
    /// The embedded artifact, verified, or a withdrawal that says why.
    ///
    /// The error is returned rather than swallowed so the caller can log it at
    /// a level a human will see, and so the refusal is testable. Nothing here
    /// decides to run without a candidate; that decision belongs to the caller.
    #[cfg(feature = "ml")]
    pub fn embedded() -> Result<Self, ShadowCandidateError> {
        ShadowCandidate::embedded().map(|candidate| Self::Attached(Arc::new(candidate)))
    }

    /// No candidate. The pre-7F behaviour, available as a value so rollback is
    /// an ordinary state rather than a special code path.
    pub fn withdrawn() -> Self {
        Self::Withdrawn
    }

    /// The attached candidate, if there is one.
    #[cfg(feature = "ml")]
    pub fn candidate(&self) -> Option<&ShadowCandidate> {
        match self {
            Self::Attached(candidate) => Some(candidate.as_ref()),
            Self::Withdrawn => None,
        }
    }

    /// The predictor an evaluation should run against.
    ///
    /// Held under the attachment's own lock only long enough to clone the `Arc`,
    /// so prediction then runs with no lock held at all. That is what makes a
    /// withdrawal safe to perform while requests are in flight: a request that
    /// already holds a predictor finishes against the model it started with, and
    /// every request after the withdrawal gets the engine's own.
    #[cfg(feature = "ml")]
    pub fn predictor(&self) -> Option<Arc<ModelEnsemblePredictor>> {
        self.candidate().map(ShadowCandidate::shared_predictor)
    }

    /// Whether a candidate is attached.
    pub fn is_attached(&self) -> bool {
        match self {
            #[cfg(feature = "ml")]
            Self::Attached(_) => true,
            Self::Withdrawn => false,
        }
    }

    /// The commit id every shadow record will name, or `None` when withdrawn.
    ///
    /// In the withdrawn state this is `None` rather than the engine's pinned
    /// commit id: this module does not own that commit and will not claim it.
    #[cfg(feature = "ml")]
    pub fn attached_commit_id(&self) -> Option<&str> {
        self.candidate().map(ShadowCandidate::commit_id)
    }
}
